language: ruby
rvm:
  - 2.7.1
bundler_args: --jobs=2
script:
  - bundle exec rails db:create
  - bundle exec rails db:schema:load
  - bundle exec rspec
cache: bundler
services:
  - postgresql
addons:
  postgresql: "12.4"
